In [1]:
from eeng.client.assessment import create_confusion_matrix

In [2]:
datafile = "./aoi_novascotia_output_20230815_104538_122_assessment_assessment-122.geojson"

In [3]:
create_confusion_matrix(datafile=datafile)

,Marsh,Open water,Swamp,Salt marsh,Fen,Bog,Upland,Producers
Marsh,4.00,0.0,1.0,3.0,0.0,0.0,0.0,50.00
Open water,8.00,174.0,0.0,7.0,0.0,0.0,0.0,92.06
Swamp,3.00,0.0,19.0,0.0,3.0,0.0,2.0,70.37
Salt marsh,0.00,0.0,0.0,6.0,0.0,0.0,0.0,100.00
Fen,1.00,0.0,0.0,0.0,1.0,2.0,0.0,25.00
Bog,0.00,0.0,0.0,0.0,1.0,3.0,0.0,75.00
Upland,2.00,0.0,0.0,0.0,0.0,0.0,14.0,87.50
Consumers,22.00,100.0,95.0,38.0,20.0,60.0,88.0,NaN
Overall Accuracy,87.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN